---
id: omotesandorb-48
base_name: slide
tags: ['ruby']
presentation_date: '2019-07-04'
version: 1.0.1
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user: 
  speaker_deck_user: 
